#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_CLAN_INDEX = $(INC)
CFLAGS_CLAN_INDEX = $(CFLAGS) -O3 -std=c++11 -Wall
RESINC_CLAN_INDEX = $(RESINC)
RCFLAGS_CLAN_INDEX = $(RCFLAGS)
LIBDIR_CLAN_INDEX = $(LIBDIR)
LIB_CLAN_INDEX = $(LIB)
LDFLAGS_CLAN_INDEX = $(LDFLAGS)
OBJDIR_CLAN_INDEX = objs
DEP_CLAN_INDEX = 
OUT_CLAN_INDEX = ../bin/clan_index

INC_CLAN_SEARCH = $(INC)
CFLAGS_CLAN_SEARCH = $(CFLAGS) -O3 -std=c++11 -Wall
RESINC_CLAN_SEARCH = $(RESINC)
RCFLAGS_CLAN_SEARCH = $(RCFLAGS)
LIBDIR_CLAN_SEARCH = $(LIBDIR)
LIB_CLAN_SEARCH = $(LIB)
LDFLAGS_CLAN_SEARCH = $(LDFLAGS)
OBJDIR_CLAN_SEARCH = objs
DEP_CLAN_SEARCH = 
OUT_CLAN_SEARCH = ../bin/clan_search

INC_CLAN_OUTPUT = $(INC)
CFLAGS_CLAN_OUTPUT = $(CFLAGS) -O3 -std=c++11 -Wall
RESINC_CLAN_OUTPUT = $(RESINC)
RCFLAGS_CLAN_OUTPUT = $(RCFLAGS)
LIBDIR_CLAN_OUTPUT = $(LIBDIR)
LIB_CLAN_OUTPUT = $(LIB)
LDFLAGS_CLAN_OUTPUT = $(LDFLAGS)
OBJDIR_CLAN_OUTPUT = objs
DEP_CLAN_OUTPUT = 
OUT_CLAN_OUTPUT = ../bin/clan_output

INC_CLAN_ANNOTATE = $(INC)
CFLAGS_CLAN_ANNOTATE = $(CFLAGS) -O3 -std=c++11 -Wall
RESINC_CLAN_ANNOTATE = $(RESINC)
RCFLAGS_CLAN_ANNOTATE = $(RCFLAGS)
LIBDIR_CLAN_ANNOTATE = $(LIBDIR)
LIB_CLAN_ANNOTATE = $(LIB)
LDFLAGS_CLAN_ANNOTATE = $(LDFLAGS)
OBJDIR_CLAN_ANNOTATE = objs
DEP_CLAN_ANNOTATE = 
OUT_CLAN_ANNOTATE = ../bin/clan_annotate

OBJ_CLAN_INDEX = $(OBJDIR_CLAN_INDEX)/__/src/output_printer.o $(OBJDIR_CLAN_INDEX)/__/src/loader.o $(OBJDIR_CLAN_INDEX)/__/src/main_index.o $(OBJDIR_CLAN_INDEX)/__/src/mapping_driver.o $(OBJDIR_CLAN_INDEX)/__/src/minimizer_sort.o $(OBJDIR_CLAN_INDEX)/__/src/read_merge.o $(OBJDIR_CLAN_INDEX)/__/src/sssort.o $(OBJDIR_CLAN_INDEX)/__/src/trsort.o $(OBJDIR_CLAN_INDEX)/__/src/utils.o $(OBJDIR_CLAN_INDEX)/__/src/bio_alphabet.o $(OBJDIR_CLAN_INDEX)/__/src/bwt.o $(OBJDIR_CLAN_INDEX)/__/src/bwt_frag_merger.o $(OBJDIR_CLAN_INDEX)/__/src/bwt_search.o $(OBJDIR_CLAN_INDEX)/__/src/concatenator.o $(OBJDIR_CLAN_INDEX)/__/src/dimer_folding.o $(OBJDIR_CLAN_INDEX)/__/src/divsufsort.o $(OBJDIR_CLAN_INDEX)/__/src/kmer_unitcoder.o

OBJ_CLAN_SEARCH = $(OBJDIR_CLAN_SEARCH)/__/src/output_printer.o $(OBJDIR_CLAN_SEARCH)/__/src/loader.o $(OBJDIR_CLAN_SEARCH)/__/src/main_search.o $(OBJDIR_CLAN_SEARCH)/__/src/mapping_driver.o $(OBJDIR_CLAN_SEARCH)/__/src/minimizer_sort.o $(OBJDIR_CLAN_SEARCH)/__/src/read_merge.o $(OBJDIR_CLAN_SEARCH)/__/src/sssort.o $(OBJDIR_CLAN_SEARCH)/__/src/trsort.o $(OBJDIR_CLAN_SEARCH)/__/src/utils.o $(OBJDIR_CLAN_SEARCH)/__/src/bio_alphabet.o $(OBJDIR_CLAN_SEARCH)/__/src/bwt.o $(OBJDIR_CLAN_SEARCH)/__/src/bwt_frag_merger.o $(OBJDIR_CLAN_SEARCH)/__/src/bwt_search.o $(OBJDIR_CLAN_SEARCH)/__/src/concatenator.o $(OBJDIR_CLAN_SEARCH)/__/src/dimer_folding.o $(OBJDIR_CLAN_SEARCH)/__/src/divsufsort.o $(OBJDIR_CLAN_SEARCH)/__/src/kmer_unitcoder.o

OBJ_CLAN_OUTPUT = $(OBJDIR_CLAN_OUTPUT)/__/src/output_printer.o $(OBJDIR_CLAN_OUTPUT)/__/src/loader.o $(OBJDIR_CLAN_OUTPUT)/__/src/main_output.o $(OBJDIR_CLAN_OUTPUT)/__/src/mapping_driver.o $(OBJDIR_CLAN_OUTPUT)/__/src/minimizer_sort.o $(OBJDIR_CLAN_OUTPUT)/__/src/read_merge.o $(OBJDIR_CLAN_OUTPUT)/__/src/sssort.o $(OBJDIR_CLAN_OUTPUT)/__/src/trsort.o $(OBJDIR_CLAN_OUTPUT)/__/src/utils.o $(OBJDIR_CLAN_OUTPUT)/__/src/bio_alphabet.o $(OBJDIR_CLAN_OUTPUT)/__/src/bwt.o $(OBJDIR_CLAN_OUTPUT)/__/src/bwt_frag_merger.o $(OBJDIR_CLAN_OUTPUT)/__/src/bwt_search.o $(OBJDIR_CLAN_OUTPUT)/__/src/concatenator.o $(OBJDIR_CLAN_OUTPUT)/__/src/dimer_folding.o $(OBJDIR_CLAN_OUTPUT)/__/src/divsufsort.o $(OBJDIR_CLAN_OUTPUT)/__/src/kmer_unitcoder.o

OBJ_CLAN_ANNOTATE = $(OBJDIR_CLAN_ANNOTATE)/__/src/output_printer.o $(OBJDIR_CLAN_ANNOTATE)/__/src/loader.o $(OBJDIR_CLAN_ANNOTATE)/__/src/main_annotate.o $(OBJDIR_CLAN_ANNOTATE)/__/src/mapping_driver.o $(OBJDIR_CLAN_ANNOTATE)/__/src/minimizer_sort.o $(OBJDIR_CLAN_ANNOTATE)/__/src/read_merge.o $(OBJDIR_CLAN_ANNOTATE)/__/src/sssort.o $(OBJDIR_CLAN_ANNOTATE)/__/src/trsort.o $(OBJDIR_CLAN_ANNOTATE)/__/src/utils.o $(OBJDIR_CLAN_ANNOTATE)/__/src/bio_alphabet.o $(OBJDIR_CLAN_ANNOTATE)/__/src/bwt.o $(OBJDIR_CLAN_ANNOTATE)/__/src/bwt_frag_merger.o $(OBJDIR_CLAN_ANNOTATE)/__/src/bwt_search.o $(OBJDIR_CLAN_ANNOTATE)/__/src/concatenator.o $(OBJDIR_CLAN_ANNOTATE)/__/src/dimer_folding.o $(OBJDIR_CLAN_ANNOTATE)/__/src/divsufsort.o $(OBJDIR_CLAN_ANNOTATE)/__/src/kmer_unitcoder.o

all: clan_index clan_search clan_output clan_annotate

clean: clean_clan_index clean_clan_search clean_clan_output clean_clan_annotate

before_clan_index: 
	test -d ../bin || mkdir -p ../bin
	test -d $(OBJDIR_CLAN_INDEX)/__/src || mkdir -p $(OBJDIR_CLAN_INDEX)/__/src

after_clan_index: 

clan_index: before_clan_index out_clan_index after_clan_index

out_clan_index: before_clan_index $(OBJ_CLAN_INDEX) $(DEP_CLAN_INDEX)
	$(LD) $(LIBDIR_CLAN_INDEX) -o $(OUT_CLAN_INDEX) $(OBJ_CLAN_INDEX)  $(LDFLAGS_CLAN_INDEX) $(LIB_CLAN_INDEX)

$(OBJDIR_CLAN_INDEX)/__/src/output_printer.o: ../src/output_printer.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/output_printer.cc -o $(OBJDIR_CLAN_INDEX)/__/src/output_printer.o

$(OBJDIR_CLAN_INDEX)/__/src/loader.o: ../src/loader.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/loader.cc -o $(OBJDIR_CLAN_INDEX)/__/src/loader.o

$(OBJDIR_CLAN_INDEX)/__/src/main_index.o: ../src/main_index.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/main_index.cc -o $(OBJDIR_CLAN_INDEX)/__/src/main_index.o

$(OBJDIR_CLAN_INDEX)/__/src/mapping_driver.o: ../src/mapping_driver.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/mapping_driver.cc -o $(OBJDIR_CLAN_INDEX)/__/src/mapping_driver.o

$(OBJDIR_CLAN_INDEX)/__/src/minimizer_sort.o: ../src/minimizer_sort.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/minimizer_sort.cc -o $(OBJDIR_CLAN_INDEX)/__/src/minimizer_sort.o

$(OBJDIR_CLAN_INDEX)/__/src/read_merge.o: ../src/read_merge.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/read_merge.cc -o $(OBJDIR_CLAN_INDEX)/__/src/read_merge.o

$(OBJDIR_CLAN_INDEX)/__/src/sssort.o: ../src/sssort.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/sssort.cc -o $(OBJDIR_CLAN_INDEX)/__/src/sssort.o

$(OBJDIR_CLAN_INDEX)/__/src/trsort.o: ../src/trsort.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/trsort.cc -o $(OBJDIR_CLAN_INDEX)/__/src/trsort.o

$(OBJDIR_CLAN_INDEX)/__/src/utils.o: ../src/utils.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/utils.cc -o $(OBJDIR_CLAN_INDEX)/__/src/utils.o

$(OBJDIR_CLAN_INDEX)/__/src/bio_alphabet.o: ../src/bio_alphabet.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/bio_alphabet.cc -o $(OBJDIR_CLAN_INDEX)/__/src/bio_alphabet.o

$(OBJDIR_CLAN_INDEX)/__/src/bwt.o: ../src/bwt.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/bwt.cc -o $(OBJDIR_CLAN_INDEX)/__/src/bwt.o

$(OBJDIR_CLAN_INDEX)/__/src/bwt_frag_merger.o: ../src/bwt_frag_merger.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/bwt_frag_merger.cc -o $(OBJDIR_CLAN_INDEX)/__/src/bwt_frag_merger.o

$(OBJDIR_CLAN_INDEX)/__/src/bwt_search.o: ../src/bwt_search.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/bwt_search.cc -o $(OBJDIR_CLAN_INDEX)/__/src/bwt_search.o

$(OBJDIR_CLAN_INDEX)/__/src/concatenator.o: ../src/concatenator.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/concatenator.cc -o $(OBJDIR_CLAN_INDEX)/__/src/concatenator.o

$(OBJDIR_CLAN_INDEX)/__/src/dimer_folding.o: ../src/dimer_folding.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/dimer_folding.cc -o $(OBJDIR_CLAN_INDEX)/__/src/dimer_folding.o

$(OBJDIR_CLAN_INDEX)/__/src/divsufsort.o: ../src/divsufsort.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/divsufsort.cc -o $(OBJDIR_CLAN_INDEX)/__/src/divsufsort.o

$(OBJDIR_CLAN_INDEX)/__/src/kmer_unitcoder.o: ../src/kmer_unitcoder.cc
	$(CC) $(CFLAGS_CLAN_INDEX) $(INC_CLAN_INDEX) -c ../src/kmer_unitcoder.cc -o $(OBJDIR_CLAN_INDEX)/__/src/kmer_unitcoder.o

clean_clan_index: 
	rm -f $(OBJ_CLAN_INDEX) $(OUT_CLAN_INDEX)
	rm -rf ../bin
	rm -rf $(OBJDIR_CLAN_INDEX)/__/src

before_clan_search: 
	test -d ../bin || mkdir -p ../bin
	test -d $(OBJDIR_CLAN_SEARCH)/__/src || mkdir -p $(OBJDIR_CLAN_SEARCH)/__/src

after_clan_search: 

clan_search: before_clan_search out_clan_search after_clan_search

out_clan_search: before_clan_search $(OBJ_CLAN_SEARCH) $(DEP_CLAN_SEARCH)
	$(LD) $(LIBDIR_CLAN_SEARCH) -o $(OUT_CLAN_SEARCH) $(OBJ_CLAN_SEARCH)  $(LDFLAGS_CLAN_SEARCH) $(LIB_CLAN_SEARCH)

$(OBJDIR_CLAN_SEARCH)/__/src/output_printer.o: ../src/output_printer.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/output_printer.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/output_printer.o

$(OBJDIR_CLAN_SEARCH)/__/src/loader.o: ../src/loader.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/loader.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/loader.o

$(OBJDIR_CLAN_SEARCH)/__/src/main_search.o: ../src/main_search.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/main_search.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/main_search.o

$(OBJDIR_CLAN_SEARCH)/__/src/mapping_driver.o: ../src/mapping_driver.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/mapping_driver.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/mapping_driver.o

$(OBJDIR_CLAN_SEARCH)/__/src/minimizer_sort.o: ../src/minimizer_sort.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/minimizer_sort.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/minimizer_sort.o

$(OBJDIR_CLAN_SEARCH)/__/src/read_merge.o: ../src/read_merge.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/read_merge.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/read_merge.o

$(OBJDIR_CLAN_SEARCH)/__/src/sssort.o: ../src/sssort.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/sssort.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/sssort.o

$(OBJDIR_CLAN_SEARCH)/__/src/trsort.o: ../src/trsort.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/trsort.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/trsort.o

$(OBJDIR_CLAN_SEARCH)/__/src/utils.o: ../src/utils.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/utils.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/utils.o

$(OBJDIR_CLAN_SEARCH)/__/src/bio_alphabet.o: ../src/bio_alphabet.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/bio_alphabet.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/bio_alphabet.o

$(OBJDIR_CLAN_SEARCH)/__/src/bwt.o: ../src/bwt.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/bwt.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/bwt.o

$(OBJDIR_CLAN_SEARCH)/__/src/bwt_frag_merger.o: ../src/bwt_frag_merger.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/bwt_frag_merger.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/bwt_frag_merger.o

$(OBJDIR_CLAN_SEARCH)/__/src/bwt_search.o: ../src/bwt_search.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/bwt_search.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/bwt_search.o

$(OBJDIR_CLAN_SEARCH)/__/src/concatenator.o: ../src/concatenator.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/concatenator.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/concatenator.o

$(OBJDIR_CLAN_SEARCH)/__/src/dimer_folding.o: ../src/dimer_folding.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/dimer_folding.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/dimer_folding.o

$(OBJDIR_CLAN_SEARCH)/__/src/divsufsort.o: ../src/divsufsort.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/divsufsort.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/divsufsort.o

$(OBJDIR_CLAN_SEARCH)/__/src/kmer_unitcoder.o: ../src/kmer_unitcoder.cc
	$(CC) $(CFLAGS_CLAN_SEARCH) $(INC_CLAN_SEARCH) -c ../src/kmer_unitcoder.cc -o $(OBJDIR_CLAN_SEARCH)/__/src/kmer_unitcoder.o

clean_clan_search: 
	rm -f $(OBJ_CLAN_SEARCH) $(OUT_CLAN_SEARCH)
	rm -rf ../bin
	rm -rf $(OBJDIR_CLAN_SEARCH)/__/src

before_clan_output: 
	test -d ../bin || mkdir -p ../bin
	test -d $(OBJDIR_CLAN_OUTPUT)/__/src || mkdir -p $(OBJDIR_CLAN_OUTPUT)/__/src

after_clan_output: 

clan_output: before_clan_output out_clan_output after_clan_output

out_clan_output: before_clan_output $(OBJ_CLAN_OUTPUT) $(DEP_CLAN_OUTPUT)
	$(LD) $(LIBDIR_CLAN_OUTPUT) -o $(OUT_CLAN_OUTPUT) $(OBJ_CLAN_OUTPUT)  $(LDFLAGS_CLAN_OUTPUT) $(LIB_CLAN_OUTPUT)

$(OBJDIR_CLAN_OUTPUT)/__/src/output_printer.o: ../src/output_printer.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/output_printer.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/output_printer.o

$(OBJDIR_CLAN_OUTPUT)/__/src/loader.o: ../src/loader.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/loader.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/loader.o

$(OBJDIR_CLAN_OUTPUT)/__/src/main_output.o: ../src/main_output.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/main_output.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/main_output.o

$(OBJDIR_CLAN_OUTPUT)/__/src/mapping_driver.o: ../src/mapping_driver.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/mapping_driver.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/mapping_driver.o

$(OBJDIR_CLAN_OUTPUT)/__/src/minimizer_sort.o: ../src/minimizer_sort.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/minimizer_sort.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/minimizer_sort.o

$(OBJDIR_CLAN_OUTPUT)/__/src/read_merge.o: ../src/read_merge.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/read_merge.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/read_merge.o

$(OBJDIR_CLAN_OUTPUT)/__/src/sssort.o: ../src/sssort.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/sssort.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/sssort.o

$(OBJDIR_CLAN_OUTPUT)/__/src/trsort.o: ../src/trsort.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/trsort.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/trsort.o

$(OBJDIR_CLAN_OUTPUT)/__/src/utils.o: ../src/utils.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/utils.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/utils.o

$(OBJDIR_CLAN_OUTPUT)/__/src/bio_alphabet.o: ../src/bio_alphabet.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/bio_alphabet.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/bio_alphabet.o

$(OBJDIR_CLAN_OUTPUT)/__/src/bwt.o: ../src/bwt.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/bwt.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/bwt.o

$(OBJDIR_CLAN_OUTPUT)/__/src/bwt_frag_merger.o: ../src/bwt_frag_merger.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/bwt_frag_merger.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/bwt_frag_merger.o

$(OBJDIR_CLAN_OUTPUT)/__/src/bwt_search.o: ../src/bwt_search.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/bwt_search.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/bwt_search.o

$(OBJDIR_CLAN_OUTPUT)/__/src/concatenator.o: ../src/concatenator.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/concatenator.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/concatenator.o

$(OBJDIR_CLAN_OUTPUT)/__/src/dimer_folding.o: ../src/dimer_folding.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/dimer_folding.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/dimer_folding.o

$(OBJDIR_CLAN_OUTPUT)/__/src/divsufsort.o: ../src/divsufsort.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/divsufsort.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/divsufsort.o

$(OBJDIR_CLAN_OUTPUT)/__/src/kmer_unitcoder.o: ../src/kmer_unitcoder.cc
	$(CC) $(CFLAGS_CLAN_OUTPUT) $(INC_CLAN_OUTPUT) -c ../src/kmer_unitcoder.cc -o $(OBJDIR_CLAN_OUTPUT)/__/src/kmer_unitcoder.o

clean_clan_output: 
	rm -f $(OBJ_CLAN_OUTPUT) $(OUT_CLAN_OUTPUT)
	rm -rf ../bin
	rm -rf $(OBJDIR_CLAN_OUTPUT)/__/src

before_clan_annotate: 
	test -d ../bin || mkdir -p ../bin
	test -d $(OBJDIR_CLAN_ANNOTATE)/__/src || mkdir -p $(OBJDIR_CLAN_ANNOTATE)/__/src

after_clan_annotate: 

clan_annotate: before_clan_annotate out_clan_annotate after_clan_annotate

out_clan_annotate: before_clan_annotate $(OBJ_CLAN_ANNOTATE) $(DEP_CLAN_ANNOTATE)
	$(LD) $(LIBDIR_CLAN_ANNOTATE) -o $(OUT_CLAN_ANNOTATE) $(OBJ_CLAN_ANNOTATE)  $(LDFLAGS_CLAN_ANNOTATE) $(LIB_CLAN_ANNOTATE)

$(OBJDIR_CLAN_ANNOTATE)/__/src/output_printer.o: ../src/output_printer.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/output_printer.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/output_printer.o

$(OBJDIR_CLAN_ANNOTATE)/__/src/loader.o: ../src/loader.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/loader.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/loader.o

$(OBJDIR_CLAN_ANNOTATE)/__/src/main_annotate.o: ../src/main_annotate.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/main_annotate.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/main_annotate.o

$(OBJDIR_CLAN_ANNOTATE)/__/src/mapping_driver.o: ../src/mapping_driver.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/mapping_driver.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/mapping_driver.o

$(OBJDIR_CLAN_ANNOTATE)/__/src/minimizer_sort.o: ../src/minimizer_sort.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/minimizer_sort.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/minimizer_sort.o

$(OBJDIR_CLAN_ANNOTATE)/__/src/read_merge.o: ../src/read_merge.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/read_merge.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/read_merge.o

$(OBJDIR_CLAN_ANNOTATE)/__/src/sssort.o: ../src/sssort.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/sssort.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/sssort.o

$(OBJDIR_CLAN_ANNOTATE)/__/src/trsort.o: ../src/trsort.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/trsort.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/trsort.o

$(OBJDIR_CLAN_ANNOTATE)/__/src/utils.o: ../src/utils.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/utils.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/utils.o

$(OBJDIR_CLAN_ANNOTATE)/__/src/bio_alphabet.o: ../src/bio_alphabet.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/bio_alphabet.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/bio_alphabet.o

$(OBJDIR_CLAN_ANNOTATE)/__/src/bwt.o: ../src/bwt.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/bwt.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/bwt.o

$(OBJDIR_CLAN_ANNOTATE)/__/src/bwt_frag_merger.o: ../src/bwt_frag_merger.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/bwt_frag_merger.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/bwt_frag_merger.o

$(OBJDIR_CLAN_ANNOTATE)/__/src/bwt_search.o: ../src/bwt_search.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/bwt_search.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/bwt_search.o

$(OBJDIR_CLAN_ANNOTATE)/__/src/concatenator.o: ../src/concatenator.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/concatenator.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/concatenator.o

$(OBJDIR_CLAN_ANNOTATE)/__/src/dimer_folding.o: ../src/dimer_folding.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/dimer_folding.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/dimer_folding.o

$(OBJDIR_CLAN_ANNOTATE)/__/src/divsufsort.o: ../src/divsufsort.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/divsufsort.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/divsufsort.o

$(OBJDIR_CLAN_ANNOTATE)/__/src/kmer_unitcoder.o: ../src/kmer_unitcoder.cc
	$(CC) $(CFLAGS_CLAN_ANNOTATE) $(INC_CLAN_ANNOTATE) -c ../src/kmer_unitcoder.cc -o $(OBJDIR_CLAN_ANNOTATE)/__/src/kmer_unitcoder.o

clean_clan_annotate: 
	rm -f $(OBJ_CLAN_ANNOTATE) $(OUT_CLAN_ANNOTATE)
	rm -rf ../bin
	rm -rf $(OBJDIR_CLAN_ANNOTATE)/__/src

virtual_all: clan_index clan_search clan_output clan_annotate

.PHONY: before_clan_index after_clan_index clean_clan_index before_clan_search after_clan_search clean_clan_search before_clan_output after_clan_output clean_clan_output before_clan_annotate after_clan_annotate clean_clan_annotate

